### PR TITLE
Our first commit

### PR DESCRIPTION
**Pull request by allenyin55**

### CODE REVIEW

**Comment by jryio** [comment]
Hey Allen, Congrats on the first pull request!

A few things to remember:
- The template is there to copy, next time try not to edit it directly haha. Don't worry though, Kyle fixed it here: https://github.com/dvcoders/club-projects/commit/5485375fa18ae0004fe6bfaa8ef73d92ade2a9d2
- When making a Pull Request, you should assign someone to review your work before you merge. Usually when making Pull Requests it's a good idea to get some feedback! 

Excited about your project, and looking forward to helping you out as much as possible!

**Comment by allenyin55** [comment]
Hey Jacob,

I see what you are saying about the template, not sure about how to assign
someone to review my work though...

I am exited about our project too! So much to learn, but I am sure it will
be fun :)

Thanks
Allen

**Comment by jryio** [comment]
No worries!

The assign functionality is on the sidebar on the Pull Request on Github.

Here's a quick picture:  

screen shot 2016-02-26 at 6 58 10 pm

**Comment by allenyin55** [comment]
Got it! Thanks!

See you next meeting

**Pull request merged**
